# -*- coding: utf-8 -*-
"""moviereview11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rG_XY1iPWIX9PDkdnIeATBpGIw0VJcyT
"""

!pip install streamlit
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter

st.set_page_config(
    page_title="KGF 2 Movie Review Analyzer",
    page_icon="🎬",
    layout="wide"
)

st.title("🎬 KGF 2 Movie Review Analyzer")
st.markdown("Analyze user reviews using your trained LLM/GenAI model.")

# -----------------------------
# Session State
# -----------------------------
if "reviews" not in st.session_state:
    st.session_state.reviews = []

# -----------------------------
# Dummy Backend Function
# Replace with your LLM function
# -----------------------------
def analyze_review(review):

    review_lower = review.lower()

    positive_words = [
        "excellent", "good", "amazing", "awesome",
        "fantastic", "great", "super", "masterpiece",
        "love", "best"
    ]

    negative_words = [
        "bad", "worst", "poor", "boring",
        "waste", "terrible", "awful",
        "hate", "disappointing"
    ]

    pos = sum(word in review_lower for word in positive_words)
    neg = sum(word in review_lower for word in negative_words)

    if pos > neg:
        sentiment = "Positive 😊"
        confidence = round(70 + pos*5,2)

    elif neg > pos:
        sentiment = "Negative 😞"
        confidence = round(70 + neg*5,2)

    else:
        sentiment = "Neutral 😐"
        confidence = 60.0

    explanation = f"The review is classified as **{sentiment}**."

    return sentiment, confidence, explanation


# -----------------------------
# Review Input
# -----------------------------
review = st.text_area(
    "✍️ Enter your review",
    height=180,
    placeholder="Example: KGF 2 is one of the best action movies I have ever watched..."
)

if st.button("🔍 Analyze Review", use_container_width=True):

    if review.strip() == "":
        st.warning("Please enter a review.")

    else:

        sentiment, confidence, explanation = analyze_review(review)

        st.session_state.reviews.append(sentiment)

        col1, col2 = st.columns(2)

        with col1:
            st.success(f"### Sentiment\n{sentiment}")

        with col2:
            st.info(f"### Confidence\n{confidence}%")

        st.markdown("---")

        st.subheader("📄 Explanation")

        st.write(explanation)

# -----------------------------
# Statistics
# -----------------------------
if len(st.session_state.reviews) > 0:

    st.markdown("---")
    st.header("📊 Review Statistics")

    sentiments = Counter(st.session_state.reviews)

    total = len(st.session_state.reviews)

    c1, c2, c3 = st.columns(3)

    c1.metric("Total Reviews", total)

    c2.metric(
        "Positive",
        sentiments.get("Positive 😊",0)
    )

    c3.metric(
        "Negative",
        sentiments.get("Negative 😞",0)
    )

    df = pd.DataFrame({
        "Sentiment": sentiments.keys(),
        "Count": sentiments.values()
    })

    col1, col2 = st.columns(2)

    with col1:

        fig, ax = plt.subplots(figsize=(5,5))

        ax.pie(
            df["Count"],
            labels=df["Sentiment"],
            autopct="%1.1f%%",
            startangle=90
        )

        ax.set_title("Sentiment Distribution")

        st.pyplot(fig)

    with col2:

        fig, ax = plt.subplots(figsize=(6,4))

        ax.bar(
            df["Sentiment"],
            df["Count"]
        )

        ax.set_ylabel("Reviews")

        ax.set_title("Review Count")

        st.pyplot(fig)

# -----------------------------
# Review History
# -----------------------------
if len(st.session_state.reviews) > 0:

    st.markdown("---")
    st.subheader("📝 Review History")

    history = pd.DataFrame({
        "Review No": range(1,len(st.session_state.reviews)+1),
        "Sentiment": st.session_state.reviews
    })

    st.dataframe(
        history,
        use_container_width=True
    )